# Generated by Django 2.1.15 on 2021-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210824_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cluster',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
