# Generated by Django 2.1.15 on 2021-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210825_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='main_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
